### ISSUE TITLE
Repeatedly changing the padding increases memory usage, causing Ubuntu to freeze.

### ISSUE THREAD

**Issue by komaki1111** [moveit/moveit#3643]
**Is your feature request related to a problem? Please describe.**
When dynamically changing the padding repeatedly, memory usage gradually increases. When memory runs out, Ubuntu freezes.
I investigated the cause.
At the end of the method `template <typename BV, typename T> FCLGeometryConstPtr createCollisionGeometry(const shapes::ShapeConstPtr& shape, const T* data, int shape_index)`, defined in collision_common.cpp, the following processing is executed.

https://github.com/moveit/moveit/blob/0ca45f0b1a582b727ec50a9a9af8fca7d8dba3bb/moveit_core/collision_detection_fcl/src/collision_common.cpp#L863-L870

When publishing a message to change the padding value, memory usage increases because memory is allocated each time by the process `cache.map_[wptr] = res;`
Although memory release is executed in the next line with `cache.bumpUseCount();`, the constant `MAX_CLEAN_COUNT` is defined as 100, so memory is not released until this function is executed 100 times.
The larger the size of the robot model file used for collision detection, the greater the memory increase.
If memory runs out before `bumpUseCount()` is executed 100 times, Ubuntu freezes.
As a test, I changed the value of the constant `MAX_CLEAN_COUNT` to 2, and the phenomenon where memory usage increased each time a dynamic change message was published did not occur.
Therefore, it seems certain that the cause is the failure to release memory due to the `bumpUseCount()` method not being executed.
Since this leads to system freezes, I would like to request a fix to prevent memory usage from continuously increasing.

**Describe the solution you'd like**
I would like to request that memory usage does not continue to increase. For example, by reducing the value of MAX_CLEAN_COUNT.

**Environment**
・VirtualBox 6.1.48
・Ubuntu 20.04
・ROS noetic

**Step to reproduce**
1. Follow the instructions on the following page to install the Universal Robot environment.
    https://github.com/ros-industrial/universal_robot
2. Configure the robot model file used for robot visualization to also be used for collision detection.
　　By default, the robot model file used for collision detection is very small, so the increase in memory usage cannot be observed in the system monitor. To use a large robot model file for collision detection, configure the system to use the visualization robot model. In `universal_robot/ur_description/config/ur5e/visual_parameters.yaml,` set the value of the `mesh` key under the `visual` key to the same file name as the `mesh` key under the `collision` key.

```
mesh_files:
  base:
    visual:
      mesh: "package://ur_description/meshes/ur5e/visual/base.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5e/visual/base.dae"

  shoulder:
    visual:
      mesh: "package://ur_description/meshes/ur5e/visual/shoulder.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5e/visual/shoulder.dae"
```

3. Start the Ubuntu System Monitor.
4. Launch the UR5e environment with following command.
    `$ roslaunch ur5e_moveit_config demo.launch`
5. Open new terminal window.
6. Repeat the following.
    i. Repeatedly publish the message for changing the padding to `/planning_scene` topic. The value of the `padding` key needs to be changed and the value of the `is_diff` key needs to be `True` each publish.
    ii. In the system monitor, check that the memory usage increases with each publish.

![memIncreaseSysMoni](https://github.com/user-attachments/assets/32385715-3023-49fd-9f90-03036c17656a)
