### ISSUE TITLE
Repeatedly changing the padding increases memory usage, causing Ubuntu to freeze.

### ISSUE THREAD

**Issue by komaki1111** [moveit/moveit#3644]
**Is your feature request related to a problem? Please describe.**
When dynamically changing the padding repeatedly, memory usage gradually increases. When memory runs out, Ubuntu freezes.
I investigated the cause.
At the end of the method `template <typename BV, typename T> FCLGeometryConstPtr createCollisionGeometry(const shapes::ShapeConstPtr& shape, const T* data, int shape_index)`, defined in collision_common.cpp, the following processing is executed.

https://github.com/moveit/moveit/blob/0ca45f0b1a582b727ec50a9a9af8fca7d8dba3bb/moveit_core/collision_detection_fcl/src/collision_common.cpp#L863-L870

When publishing a message to change the padding value, memory usage increases because memory is allocated each time by the process `cache.map_[wptr] = res;`. Although memory release is executed in the next line with `cache.bumpUseCount();`, the constant `MAX_CLEAN_COUNT` is defined as 100, so memory is not released until this function is executed 100 times. The larger the size of the robot model file used for collision detection, the greater the memory increase. If memory runs out before `bumpUseCount()` is executed 100 times, Ubuntu freezes.
As a test, I changed the value of the constant `MAX_CLEAN_COUNT` to 2, and the phenomenon where memory usage increased each time a dynamic change message was published did not occur. Therefore, it seems certain that the cause is the failure to release memory due to the `bumpUseCount()` method not being executed.
Since this leads to system freezes, I would like to request a fix to prevent memory usage from continuously increasing.

**Describe the solution you'd like**
I would like to request that memory usage does not continue to increase. For example, by reducing the value of `MAX_CLEAN_COUNT`.

**Environment**
・VirtualBox 6.1.48
・Ubuntu 20.04
・ROS noetic

**Step to reproduce**
1. Follow the instructions on the following page to install the Universal Robot environment.
https://github.com/ros-industrial/universal_robot
2. Configure the robot model file used for robot visualization to also be used for collision detection.
By default, the robot model file used for collision detection is very small, so the increase in memory usage cannot be observed in the system monitor. To use a large robot model file for collision detection, configure the system to use the visualization robot model. In `universal_robot/ur_description/config/ur5e/visual_parameters.yaml`, copy the file names from the `visual-mesh` key to the `collision-mesh` key for all robot links. Below is a part of it.
```
  base:
    visual:
      mesh: "package://ur_description/meshes/ur5e/visual/base.dae"
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh: "package://ur_description/meshes/ur5e/visual/base.dae"
```
3. Start the Ubuntu System Monitor.
4. Launch the UR5e environment with following command.
`$ roslaunch ur5e_moveit_config demo.launch`
5. Open new terminal window.
6. In the newly opened window, repeatedly enter the following command to make dynamic changes to the padding. The value of the `padding` key needs to be changed and the value of the `is_diff` key needs to be `True` each publish.
```
rostopic pub -1 /planning_scene moveit_msgs/PlanningScene "name: ''
robot_state: 
  joint_state: 
    header: 
      seq: 0
      stamp: 
        secs: 0
        nsecs:         0
      frame_id: "base_link"
    name: 
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    velocity: []
    effort: []
  multi_dof_joint_state: 
    header: 
      seq: 0
      stamp: 
        secs: 0
        nsecs:         0
      frame_id: "base_link"
    joint_names: []
    transforms: []
    twist: []
    wrench: []
  attached_collision_objects: []
  is_diff: False
robot_model_name: "ur5e_robot"
fixed_frame_transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 0
        nsecs:         0
      frame_id: "base_link"
    child_frame_id: "base_link"
    transform: 
      translation: 
        x: 0.0
        y: 0.0
        z: 0.0
      rotation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
allowed_collision_matrix: 
  entry_names: 
    - base_link_inertia
    - forearm_link
    - shoulder_link
    - upper_arm_link
    - wrist_1_link
    - wrist_2_link
    - wrist_3_link
  entry_values: 
    - 
      enabled: [False, False, True, True, True, False, False]
    - 
      enabled: [False, False, False, True, True, False, False]
    - 
      enabled: [True, False, False, True, True, True, False]
    - 
      enabled: [True, True, True, False, False, False, False]
    - 
      enabled: [True, True, True, False, False, True, True]
    - 
      enabled: [False, False, True, False, True, False, True]
    - 
      enabled: [False, False, False, False, True, True, False]
  default_entry_names: []
  default_entry_values: []
link_padding: 
  - 
    link_name: "base_link_inertia"
    padding: 0.3
  - 
    link_name: "forearm_link"
    padding: 0.3
  - 
    link_name: "shoulder_link"
    padding: 0.3
  - 
    link_name: "upper_arm_link"
    padding: 0.3
  - 
    link_name: "wrist_1_link"
    padding: 0.3
  - 
    link_name: "wrist_2_link"
    padding: 0.3
  - 
    link_name: "wrist_3_link"
    padding: 0.3
link_scale: 
  - 
    link_name: "base_link_inertia"
    scale: 1.0
  - 
    link_name: "forearm_link"
    scale: 1.0
  - 
    link_name: "shoulder_link"
    scale: 1.0
  - 
    link_name: "upper_arm_link"
    scale: 1.0
  - 
    link_name: "wrist_1_link"
    scale: 1.0
  - 
    link_name: "wrist_2_link"
    scale: 1.0
  - 
    link_name: "wrist_3_link"
    scale: 1.0
object_colors: []
world: 
  collision_objects: []
  octomap: 
    header: 
      seq: 0
      stamp: 
        secs: 0
        nsecs:         0
      frame_id: "base_link"
    origin: 
      position: 
        x: 0.0
        y: 0.0
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 0.0
    octomap: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      binary: False
      id: ''
      resolution: 0.0
      data: []
is_diff: True"
```
7. Check that the memory usage increases with each publish int the Ubuntu System Monitor
![memIncreaseSysMoni](https://github.com/user-attachments/assets/22336fd8-d31c-4248-b92d-5abfca12bf01)
