### ISSUE TITLE
joints_allowed_start_tolerance doesn't support joints with slash in their name

### ISSUE THREAD

**Issue by Hugal31** [moveit/moveit#3647]
### Description

Due to the use of `NodeHandle::getParam(std::string, std::map<std::string, double>)`, `TrajectoryExecutionManager::updateJointsAllowedStartTolerance()` doesn't work if a joint has a slash in its name.

### Your environment
* ROS Distro: Noetic
* OS Version: e.g. Ubuntu 20.04
* Binary build 1.1.14-1focal.20240812.164411

### Steps to reproduce

Fill `move_group/trajectory_execution/joints_allowed_start_tolerance` with values for a joint with a slash in its name, e.g.

```yaml
move_group:
  trajectory_execution:
    joints_allowed_start_tolerance:
      ur5e/shoulder_pan_joint: 0.05
```

### Expected behaviour
The TrajectoryExecutionManager should take in account the values in `joints_allowed_start_tolerance`

### Actual behaviour
It doesn't
