### ISSUE TITLE
ABORTED: TIMED_OUT when i run hardware

### ISSUE THREAD

**Issue by Mohammad-Khaliafah** [moveit/moveit#3679]
Hello everyone,

I'm encountering an issue with my robotic system and would appreciate your insights.

Problem Description:

When launching the hardware, I receive the following error messages:

[ERROR] [1735031784.794243270]: Controller is taking too long to execute trajectory (the expected upper bound for the trajectory execution was 4.192990 seconds). Stopping trajectory.
[ INFO] [1735031784.794457591]: Cancelling execution for /frrobot/fr5v6g_arm_controller
[ INFO] [1735031784.794697687]: Completed trajectory execution with status TIMED_OUT ...
[ INFO] [1735031784.795971630]: Controller '/frrobot/fr5v6g_arm_controller' successfully finished
[ INFO] [1735031784.827509122]: ABORTED: TIMED_OUT

[frrobot/frrobot_hardware_interface-5] process has died [pid 117910, exit code -6, cmd /home/mk/frcobot_ck/devel/lib/ros_control_boilerplate/frrobot_hw_main __name:=frrobot_hardware_interface __log:=/home/mk/.ros/log/efc449ae-c1d7-11ef-aab0-a10d75fade99/frrobot-frrobot_hardware_interface-5.log].
log file: /home/mk/.ros/log/efc449ae-c1d7-11ef-aab0-a10d75fade99/frrobot-frrobot_hardware_interface-5*.log
System Configuration:

Control Loop Settings:

loop_hz: 125
cycle_time_error_threshold: 0.01
Hardware Interface:

Joints: j1 to j6, gripper_robotiq_85_left_knuckle_joint
sim_control_mode: 0 (position control)
Joint State Controller:

publish_rate: 50
Arm Controller (/frrobot/fr5v6g_arm_controller):

Type: position_controllers/JointTrajectoryController
Joints: j1 to j6
Constraints:
goal_time: 3.0
Individual joint trajectory: 0.60
Individual joint goal: 0.15
Individual Joint Position Controllers:

Type: position_controllers/JointPositionController
PID: {p: 100.0, i: 0.01, d: 10.0}
Gripper Controller (/frrobot/gripper_controller):

Type: position_controllers/JointTrajectoryController
Joint: gripper_robotiq_85_left_knuckle_joint
Constraints:
goal_time: 3.0
Trajectory: 0.60
Goal: 0.15
Observations:

The system reports that the controller is taking too long to execute the trajectory, exceeding the expected duration and resulting in a timeout.
The hardware interface process terminates with exit code -6 (SIGABRT), indicating an abort signal, possibly due to an internal error or assertion failure.
Steps Taken:

Verified the controller configurations and constraints.
Ensured that the hardware interface is correctly set up.
Monitored system resources to rule out performance bottlenecks.
Request for Assistance:

ROS Distribution: [ Noetic]
Operating System: [Ubuntu 20.04]
Robot Model: FR5V6

Has anyone encountered similar issues with trajectory execution timeouts and process terminations in ROS control systems? I would appreciate any guidance on potential causes or solutions to this problem.

Thank you in advance for your help.

This is my controller.yaml  

```
# ros_control_boilerplate Settings -----------------------
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 125
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
hardware_interface:
   joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
      - gripper_robotiq_85_left_knuckle_joint
   sim_control_mode: 0 # 0: position, 1: velocity

# Publish all joint states ----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 50
/frrobot/fr5v6g_arm_controller:
   type: position_controllers/JointTrajectoryController
   # These joints can likely just be copied from the hardware_interface list above
   joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
   constraints:
      goal_time: 3.0
      #stopped_position_tolerance: 0.4 # Defaults to 0.01
      j1:
          trajectory: 0.60
          goal:       0.15
      j2:
          trajectory: 0.60
          goal:       0.15
      j3:
          trajectory: 0.60
          goal:       0.15
      j4:
          trajectory: 0.60
          goal:       0.15
      j5:
          trajectory: 0.60
          goal:       0.15
      j6:
          trajectory: 0.60
          goal:       0.15
 #  gains:
  #     joint1: {p: 2.0,  i: 0.0, d: 0.01, i_clamp: 1}
  #     joint2: {p: 2.0,  i: 0.0, d: 0.01, i_clamp: 1}

  #    state_publish_rate:  50 # Defaults to 50
  #   action_monitor_rate: 20 # Defaults to 20
  #   hold_trajectory_duration: 0 # Defaults to 0.5

# Individual Position Controllers ---------------------------------------
# Allows to send individual ROS msg of Float64 to each joint separately
joint1_position_controller:
   type: position_controllers/JointPositionController
   joint: j1
   pid: {p: 100.0, i: 0.01, d: 10.0}
joint2_position_controller:
   type: position_controllers/JointPositionController
   joint: j2
   pid: {p: 100.0, i: 0.01, d: 10.0}
joint3_position_controller:
   type: position_controllers/JointPositionController
   joint: j3
   pid: {p: 100.0, i: 0.01, d: 10.0}
joint4_position_controller:
   type: position_controllers/JointPositionController
   joint: j4
   pid: {p: 100.0, i: 0.01, d: 10.0}
joint5_position_controller:
   type: position_controllers/JointPositionController
   joint: j5
   pid: {p: 100.0, i: 0.01, d: 10.0}
joint6_position_controller:
   type: position_controllers/JointPositionController
   joint: j6
   pid: {p: 100.0, i: 0.01, d: 10.0}

/frrobot/gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
      - gripper_robotiq_85_left_knuckle_joint
  constraints:
      goal_time: 3.0
      gripper_robotiq_85_left_knuckle_joint:
          trajectory: 0.60
          goal:       0.15
jointg_position_controller:
   type: position_controllers/JointPositionController
   joint: gripper_robotiq_85_left_knuckle_joint
   pid: {p: 100.0, i: 0.01, d: 10.0}

joints_position_controller:
   type: position_controllers/JointGroupPositionController
   joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
      - gripper_robotiq_85_left_knuckle_joint

```
